server:
    port: 10088
    context-path:
logging:
  level:
      com.boxfish: DEBUG

spring:
    profiles:
      active: development
    datasource:
        name: test
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
      view:
        prefix:



---
spring:
  profiles: development

  datasource:
    url: jdbc:mysql://192.168.0.100:3306/portal_boxfish?useUnicode=true&characterEncoding=utf8
    username: boxfish
    password: boxfish

  thymeleaf:
    cache: false


---
spring:
  profiles: production

  datasource:
    url: jdbc:mysql://boxfishdb2013.mysql.rds.aliyuncs.com/bebase?useUnicode=true&characterEncoding=utf8
    username: bebase
    password: boxfish